services:
  mysql:
    image: mysql:8.0.41-debian
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - gabxdev-db:/var/lib/mysql
volumes:
  gabxdev-db: