spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: Itau Unibanco - Desafio de Programacao
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  jackson:
    time-zone: UTC
logging:
  level:
    br.com.gabxdev: debug

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      show-details: always

springdoc:
  show-actuator: true
