scrape_configs:
  - job_name: "desafio-tecnico-itau-app"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8089']
        labels:
          application: "itau-desafio-gabxdev"